name: Audit Homebrew Formula
description: Verifies given formula by `brew audit`
inputs:
  formula:
    description: name of target formula
    required: true
runs:
  using: composite
  steps:
    # https://github.com/Homebrew/actions/tree/master/setup-homebrew
    # This will clone this repo into $(brew --repo "$GITHUB_REPOSITORY")
    - id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - id: cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ runner.os }}-rubygems-
    - if: steps.cache.outputs.cache-hit != 'true'
      run: brew install-bundler-gems
      shell: bash
    - run: brew audit --strict --online ${{ github.repository }}/${{ inputs.formula }}
      shell: bash
